services:
  github-runner:
    image: __IMAGE__
    container_name: github-runner
    restart: always
    volumes:
      - ../github:/stacks/github
      - ../../volumes/github-runner:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REG_TOKEN: "__REG_TOKEN__"
      NAME: "github-alpine-byli-1"
      WORKDIR: "/home/runner/projects"
      ORGANIZATION: "byli-dev"