name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*-*-*'
env:
  TARGETOS: linux
  TARGETARCH: amd64
  RUNNER_VERSION: 2.323.0
  PROJECT_NAME: ${{ github.event.repository.name }}
  TAG_NAME: ${{ github.ref_name }}
  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build . \
            --build-arg RUNNER_VERSION=${RUNNER_VERSION} \
            --build-arg TARGETOS=${TARGETOS} \
            --build-arg TARGETARCH=${TARGETARCH} \
            -t $IMAGE

      - name: Log in to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push $IMAGE

      - name: Deploy Docker Stack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s|__IMAGE__|$IMAGE|" ./docker-compose.yml
          sed -i "s|__REG_TOKEN__|${{ secrets.REG_TOKEN }}|" ./docker-compose.yml
          mv ./docker-compose.yml /stacks/github/$PROJECT_NAME.yml
          docker stack deploy --compose-file /stacks/github/$PROJECT_NAME.yml $PROJECT_NAME >> /dev/null